name: CI

on:
  pull_request:
    branches: [develop, main]
  push:
    branches: [develop]

permissions:
  contents: read

env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Cache Next.js build cache
        uses: actions/cache@v4
        with:
          path: '**/.next/cache'
          key: next-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/tsconfig.json', '**/next.config.*') }}
          restore-keys: |
            next-cache-${{ runner.os }}-
      - name: Install deps (lockfile-aware)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
      - name: Lint
        run: npm run lint --if-present

  test:
    name: test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps (lockfile-aware)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
      - name: Unit test
        run: npm test --if-present -- --ci --reporters=default --watchAll=false

  build:
    name: build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps (lockfile-aware)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi
      # Hindari gagal build untuk PR dari fork (secrets tidak tersedia)
      - name: Build
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
        run: npm run build

      - name: Upload artifact (dist/.next/build)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: |
            dist
            build
            .next
          if-no-files-found: ignore
